export const DefaultStateImage: Record<string, any> = require("../assets/images/United-States-Country-Outline.jpg");


export function getStateImage(stateName: string): string {
  return `../assets/images/${stateName}-Outline-Map.jpg`;
}

export const stateImages: Record<string, any> = {
  AL: require("../assets/images/Alabama-Outline-Map.jpg"),
  AK: require("../assets/images/Alaska-Outline-Map.jpg"),
  AZ: require("../assets/images/Arizona-Outline-Map.jpg"),
  AR: require("../assets/images/Arkansas-Outline-Map.jpg"),
  CA: require("../assets/images/California-Outline-Map.jpg"),
  CO: require("../assets/images/Colorado-Outline-Map.jpg"),
  CT: require("../assets/images/Connecticut-Outline-Map.jpg"),
  DE: require("../assets/images/Delaware-Outline-Map.jpg"),
  FL: require("../assets/images/Florida-Outline-Map.jpg"),
  GA: require("../assets/images/Georgia-Outline-Map.jpg"),
  HI: require("../assets/images/Hawaii-Outline-Map.jpg"),
  ID: require("../assets/images/Idaho-Outline-Map.jpg"),
  IL: require("../assets/images/Illinois-Outline-Map.jpg"),
  IN: require("../assets/images/Indiana-Outline-Map.jpg"),
  IA: require("../assets/images/Iowa-Outline-Map.jpg"),
  KS: require("../assets/images/Kansas-Outline-Map.jpg"),
  KY: require("../assets/images/Kentucky-Outline-Map.jpg"),
  LA: require("../assets/images/Louisiana-Outline-Map.jpg"),
  ME: require("../assets/images/Maine-Outline-Map.jpg"),
  MD: require("../assets/images/Maryland-Outline-Map.jpg"),
  MA: require("../assets/images/Massachusetts-Outline-Map.jpg"),
  MI: require("../assets/images/Michigan-Outline-Map.jpg"),
  MN: require("../assets/images/Minnesota-Outline-Map.jpg"),
  MS: require("../assets/images/Mississippi-Outline-Map.jpg"),
  MO: require("../assets/images/Missouri-Outline-Map.jpg"),
  MT: require("../assets/images/Montana-Outline-Map.jpg"),
  NE: require("../assets/images/Nebraska-Outline-Map.jpg"),
  NV: require("../assets/images/Nevada-Outline-Map.jpg"),
  NH: require("../assets/images/New-Hampshire-Outline-Map.jpg"),
  NJ: require("../assets/images/New-Jersey-Outline-Map.jpg"),
  NM: require("../assets/images/New-Mexico-Outline-Map.jpg"),
  NY: require("../assets/images/New-York-Outline-Map.jpg"),
  NC: require("../assets/images/North-Carolina-Outline-Map.jpg"),
  ND: require("../assets/images/North-Dakota-Outline-Map.jpg"),
  OH: require("../assets/images/Ohio-Outline-Map.jpg"),
  OK: require("../assets/images/Oklahoma-Outline-Map.jpg"),
  OR: require("../assets/images/Oregon-Outline-Map.jpg"),
  PA: require("../assets/images/Pennsylvania-Outline-Map.jpg"),
  RI: require("../assets/images/Rhode-Island-Outline-Map.jpg"),
  SC: require("../assets/images/South-Carolina-Outline-Map.jpg"),
  SD: require("../assets/images/South-Dakota-Outline-Map.jpg"),
  TN: require("../assets/images/Tennessee-Outline-Map.jpg"),
  TX: require("../assets/images/Texas-Outline-Map.jpg"),
  UT: require("../assets/images/Utah-Outline-Map.jpg"),
  VT: require("../assets/images/Vermont-Outline-Map.jpg"),
  VA: require("../assets/images/Virginia-Outline-Map.jpg"),
  WA: require("../assets/images/Washington-Outline-Map.jpg"),
  WV: require("../assets/images/West-Virginia-Outline-Map.jpg"),
  WI: require("../assets/images/Wisconsin-Outline-Map.jpg"),
  WY: require("../assets/images/Wyoming-Outline-Map.jpg"),
  AS: DefaultStateImage,
  DC: DefaultStateImage,
  FM: DefaultStateImage,
  GU: DefaultStateImage,
  MH: DefaultStateImage,
  MP: DefaultStateImage,
  PR: DefaultStateImage,
  PW: DefaultStateImage,
  VI: DefaultStateImage
};